version: '3.8'
services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers=4
    volumes:
      - ./:/volume
    container_name: flask
    ports:
      - 5000:5000
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
    restart: always
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: always
    container_name: kafka

volumes:
  volume: