version: '3.8'
services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask

  go:
    build:
      context: ./
      dockerfile: ./golang/Dockerfile
    volumes:
      - ./volume:/volume
    container_name: goscript
    ports:
      - 8090:8090
    depends_on:
      kafka:
        condition: service_healthy
      kafka2:
        condition: service_healthy

  flask:
    build:
      context: ./
      dockerfile: ./pyscript/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers=4
    volumes:
      - ./volume:/volume
    container_name: flask
    ports:
      - 5000:5000
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
    restart: always
    container_name: zookeeper


  kafka2:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9095"
    expose:
      - "9095"
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://kafka2:29094,PLAINTEXT_HOST://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29094,PLAINTEXT_HOST://localhost:9094
    restart: always
    container_name: kafka2
    healthcheck:
      test: ["CMD", "nc", "-vz", "kafka2", "29094"]
      interval: 30s
      timeout: 10s
      retries: 5


  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9093"
    expose:
      - "9093"
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    restart: always
    container_name: kafka
    healthcheck:
        test: ["CMD", "nc", "-vz", "kafka", "29092"]
        interval: 30s
        timeout: 10s
        retries: 5
    
  cassandra:
      image: cassandra:4.1
      container_name: cassandra
      ports:
        - "9042:9042"
      restart: always
      volumes:
        - ./cassandra_data:/var/lib/cassandra
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10


volumes:
  volume: