version: '3.8'
services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers=4
    volumes:
      - ./:/volume
    container_name: flask
    ports:
      - 5000:5000
volumes:
  volume: