langComment = {
    "actionscript":'//', "ada":'--', "ansi_c":'/*|*/', "antlr":'//', "apdl":'!', "apl":'#',
    "applescript":'--', "asp":'\'', "autoit":';', "awk":'#', "b_lang":'//', "bash":'#',
    "batch":':', "bibtex":'%', "boo":'#','c' : '//', "chuck":'//', "cmake":'#', "coffeescript":'#',
    "context":'%', "cpp":'//', "crystal":'#', "csharp":'//', "css":'/*|*/', "cuda":'//',
    "dart":'//', "desktop":'#', "django":'{#|#}', "dmd":'//', "dockerfile":'#', "dot":'//',
    "eiffel":'--', "elixir":'#', "erlang":'%', "faust":'//', "fennel":';;', "fish":'#',
    "forth":'|\\', "fortran":'!', "fsharp":'//', "gap":'#', "gettext":'#', "gherkin":'#',
    "glsl":'//', "gnuplot":'#', "go":'//', "groovy":'//', "gtkrc":'#', "haskell":'--',
    "html":'<!--|-->', "icon":'#', "idl":'//', "inform":'!', "ini":'#', "Io":'#',
    "java":'//', "javascript":'//', "json":'/*|*/', "jsp":'//', "latex":'%', "ledger":'#',
    "less":'//', "lilypond":'%', "lisp":';', "logtalk":'%', "lua":'--', "makefile":'#',
    "markdown":'<!--|-->', "matlab":'#', "moonscript":'--', "myrddin":'//',
    "nemerle":'//', "nsis":'#', "objective_c":'//', "pascal":'//', "perl":'#', "php":'//',
    "pico8":'//', "pike":'//', "pkgbuild":'#', "prolog":'%', "props":'#', "protobuf":'//',
    "ps":'%', "pure":'//', "python":'#',"r" : "#", "rails":'#', "rc":'#', "rebol":';', "rest":'.. ',
    "rexx":'--', "rhtml":'<!--|-->', "rstats":'#', "ruby":'#', "rust":'//', "sass":'//',
    "scala":'//', "scheme":';', "smalltalk":'"|"', "sml":'(*)', "snobol4":'#', "sql":'#',
    "tcl":'#', "tex":'%', "text":'', "toml":'#', "vala":'//', "vb":'\'', "vbscript":'\'',
    "verilog":'//', "vhdl":'--', "wsf":'<!--|-->', "xml":'<!--|-->', "yaml":'#', "zig":'//',
    "nim":'#', "julia":'#'
}